/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void lintSemi() {
        App classUnderTest = new App();
        String path = "./src/main/resources/gates.js";
        String expected = "Line 3: Missing semicolon.";
        assertEquals(classUnderTest.lintSemi(path), expected);
    }
}
