/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void rollNotNull() {
        Library classUnderTest = new Library();
        assertNotNull("roll should return 'true'", classUnderTest.roll(1));
    }

    @Test
    public void rollLengthIsCorrect() {
        Library classUnderTest = new Library();
        assertTrue("roll should have a length of at least n", classUnderTest.roll(1).length == 1);
    }

    @Test
    public void containsDuplicates() {
        Library classUnderTest = new Library();
        int[] arr = new int[]{1,2,2};
        assertTrue("contains duplicate", classUnderTest.containsDuplicates(arr) == true);
    }

    @Test
    public void calculateAverage() {
        Library classUnderTest = new Library();
        int[] arr = new int[]{1,2,4};
        int expectedAverage = 2;
        assertTrue("average is six", classUnderTest.calculateAverage(arr) == expectedAverage );
    }

    @Test
    public void arrayArrayLowAverage() {
        Library classUnderTest = new Library();

        int[][] testArr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {5, 6, 5, 2, 5, 2, 7}
        };
        int[] expectedArr = new int[]{5, 6, 5, 2, 5, 2, 7};

        assertTrue("contains dupe", classUnderTest.arrayArrayLowAverage(testArr) == expectedArr);
    }
}
